-- Create the table
create table leaderboard (
  id bigint generated by default as identity primary key,
  name text not null,
  score bigint not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table leaderboard enable row level security;

-- Create a policy to allow anyone to select (read)
create policy "Enable read access for all users"
on "public"."leaderboard"
as PERMISSIVE
for SELECT
to public
using (
  true
);

-- Create a policy to allow anyone to insert (write)
create policy "Enable insert access for all users"
on "public"."leaderboard"
as PERMISSIVE
for INSERT
to public
with check (
  true
);
